### PR TITLE
Fix: Configuration schema for rules

### LINKED ISSUE #1025: Configuration schema is not valid when using array format to specify rules
As per the [documentation](https://sonarwhal.com/docs/user-guide/concepts/rules), we can configure rules as an array like this
```
{
    "rules": [
        "rule1:warning"
    ]
}
```

But this does not work! When running sonarwhal, i get an error saying the config schema is not valid

```
Shyjus-MacBook-Pro:sonarwhal shyju$ yarn sonarwhal https://news.ycombinator.com -f summary
yarn run v1.6.0
$ node dist/src/bin/sonarwhal https://news.ycombinator.com -f summary
Configuration schema is not valid
Error: Couldn't find any valid configuration
    at Function.fromConfig (/Users/shyju/Documents/Dev/GitHub/sonarwhal/packages/sonarwhal/dist/src/lib/config.js:188:19)
    at exports.analyze (/Users/shyju/Documents/Dev/GitHub/sonarwhal/packages/sonarwhal/dist/src/lib/cli/analyze.js:123:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Shyjus-MacBook-Pro:sonarwhal shyju$


```
I tried switching the `type` from `object` to `array` in the `config-schema.json` file, but that did not help!

## Environment

* __`sonarwhal` version:__  v1.7.0
* __`Node.js` version:__ v9.10.1
* __`npm` version:__5.8.0

### My sonarwhal config

```
{
    "connector": {
        "name": "chrome",
        "options": {
            "waitFor": 1000
        }
    },
    "formatters": ["summary"],
    "parsers": [],
    "rulesTimeout": 120000,
    "rules": [
        "amp-validator:warning",
        "sri:warning"
    ]
}

```

This also does not work

    "rules": [
        "?amp-validator",
        "?sri"
    ]

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #1025

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/getting-started/pull-requests/#commit-messagess)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [x] Added/Updated related tests.

### CODE REVIEW

**Comment by sarvaje** [comment]
This should be ready to review

File: packages/sonarwhal/tests/lib/config/config-validator.ts [hunk 1]
```diff
@@ -45,8 +106,14 @@ test('config with one formatters is valid', (t) => {
...
 
 test('config with 2 formatters is valid', (t) => {
-    const validConfigs = Object.assign({ formatters: ['json', 'stylish']}, validConfig);
+    const validConfigs = Object.assign({ formatters: ['json', 'stylish'] }, validConfig);
     const valid = configValidator.validateConfig(validConfigs as any);
 
     t.true(valid);
 });
+
+test('if the configuration is valid, it should validate', (t) => {
```
Comment (molant) [inline packages/sonarwhal/tests/lib/config/config-validator.ts]: Change the name to `if the configuration uses shorthands, it should validate`

**Comment by sarvaje** [comment]
@molant done!
