### PR TITLE
Fix: List packages missed or incompatible before install them

### LINKED ISSUE #1063: List what packages are not compatible with the sonarwhal version
The following message could be improved by listing the packages that are causing problems.

image

### PR DESCRIPTION
**Pull request by sarvaje**
Fix #1063

## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [x] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/getting-started/pull-requests/#commit-messagess)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

### CODE REVIEW

File: packages/sonarwhal/src/lib/cli/analyze.ts [hunk 1]
```diff
@@ -117,6 +117,16 @@ const setUpUserFeedback = (sonarwhalInstance: Sonarwhal, spinner: ORA) => {
     });
 };
 
+const showMissingAndIncompatiblePackages = (resources: SonarwhalResources) => {
+    if (resources.missing.length > 0) {
```
Comment (molant) [inline packages/sonarwhal/src/lib/cli/analyze.ts]: I was thinking about putting that output in the `askUserToInstallDependencies`. Can you move it there?

**Comment by sarvaje** [comment]
@molant ready for another review!

**Comment by sarvaje** [comment]
@molant done!
